Repository tungbq/devops-toolkit, pull requests merged in 2024-07, with the labels that each got.

#181 core: update tool versions
  Dockerfile
  README.md
  pr-changelog.txt
  toolkit_info.json
Labels: core, upgrade, automated-pr

#183 Ansible document improvement and minor change image name
  docs/usage/ansible_usage.md
  docs/usage/awscli_usage.md
  docs/usage/azurecli_usage.md
  docs/usage/helm_usage.md
  docs/usage/kubectl_usage.md
  docs/usage/python_usage.md
  docs/usage/terraform_usage.md
  samples/README.md
Labels: doc

#184 Update deploy-docker-image-release.yml to replace deprecated set-output
  .github/workflows/deploy-docker-image-release.yml
Labels: ci

#185 core: update tool versions
  Dockerfile
  README.md
  pr-changelog.txt
  toolkit_info.json
Labels: core, upgrade, automated-pr

#190 core: update tool versions
  Dockerfile
  README.md
  pr-changelog.txt
  toolkit_info.json
Labels: core, upgrade, automated-pr

#191 core: update tool versions
  Dockerfile
  README.md
  pr-changelog.txt
  toolkit_info.json
Labels: core, upgrade, automated-pr

#197 core: update tool versions
  Dockerfile
  README.md
  pr-changelog.txt
  toolkit_info.json
Labels: core, upgrade, automated-pr
