Repository tungbq/devops-toolkit, pull requests merged in 2024-03, with the labels that each got.

#56 ci: implement push latest image process
  .github/workflows/docker-image.yml
Labels: ci, devops

#64 release: implement ci for main push
  .github/workflows/docker-image-ci.yml
  .github/workflows/docker-image-main.yml
Labels: docker, ci

#79 core: update tool versions
  Dockerfile
  README.md
  scripts/check_version_in_toolkit.sh
Labels: core

#90 core: update tool versions
  Dockerfile
  README.md
  toolkit_info.json
Labels: core, upgrade, automated-pr

#94 sample: Add tooling sample code to toolkit
  .github/workflows/docker-image-ci.yml
  .github/workflows/docker-image-main.yml
  Dockerfile
  README.md
  samples/README.md
  samples/ansible/check_os.yml
  samples/python/rectangle_area_calculator.py
  samples/run_sample.sh
  samples/terraform/basic/main.tf
Labels: ci, core, sample

#97 core: update tool versions
  Dockerfile
  README.md
  toolkit_info.json
Labels: core, upgrade, automated-pr

#100 ci: implement auto labeler for new PR and issue
  .github/workflows/auto-labeler.yml
  .github/workflows/docker-image-ci.yml
Labels: enhancement, ci

#101 ci: fix Invalid event type: issues
  .github/workflows/auto-labeler.yml
Labels: ci

#102 ci/bug: fix the label format list
  .github/workflows/auto-labeler.yml
Labels: bug, ci

#106 core: optimize the image size
  Dockerfile
Labels: core

#114 ci: fix labeling list
  .github/workflows/auto-labeler.yml
Labels: ci

#116 doc: add the kubectl usage
  docs/usage/README.md
  docs/usage/ansible_usage.md
  docs/usage/kubectl_usage.md
  docs/usage/python_usage.md
  docs/usage/terraform_usage.md
Labels: doc

#117 doc: update the kubectl usage
  docs/usage/kubectl_usage.md
Labels: doc

#118 doc: update the helm usage
  docs/usage/helm_usage.md
  docs/usage/kubectl_usage.md
Labels: doc

#120 doc: aws cli usage
  docs/usage/README.md
  docs/usage/awscli_usage.md
Labels: doc

#121 doc: add azure cli usage
  docs/usage/README.md
  docs/usage/azurecli_usage.md
Labels: doc

#123 doc: improve the project introduction
  README.md
  docs/build/build_toolkit_image.md
Labels: doc

#124 doc: Update README.md icon
  README.md
Labels: doc

#127 doc: add usage to tool table
  README.md
Labels: doc

#128 doc: Update README.md icon
  README.md
Labels: doc

#129 doc: add devops-toolkit logo
  README.md
  assets/images/devops-toolkit.jpg
Labels: doc

#132 doc: Update samples README.md
  samples/README.md
Labels: doc

#136 core: optimize the image size and build time 🔥
  Dockerfile
  README.md
  docs/build/build_toolkit_image.md
  scripts/check_latest_version.py
  toolkit_info.json
Labels: enhancement, docker, core

#140 doc: description improvement
  README.md
Labels: doc

#141 ci: Create dockerhub-description.yml
  .github/workflows/dockerhub-description.yml
Labels: ci, doc

#142 ci: Update dockerhub-description.yml to use token
  .github/workflows/dockerhub-description.yml
Labels: ci, doc

#143 ci: Run dockerhub-description.yml on main push event
  .github/workflows/dockerhub-description.yml
Labels: ci, doc

#146 core: update tool versions
  Dockerfile
  README.md
  toolkit_info.json
Labels: core, upgrade, automated-pr
